version: "3.8"
services:
  redis:
    image: redis
    expose:
      - 6379

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "simple_db"
    ports:
    - 3306:3306
